name: Python 3.8.9 (x64)

on: [push]

jobs:

  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.8.16
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.16"
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install
      
      - name: Install Dependencies
        run: pip install pyinstaller
        
      - name: Build PyInstaller package
        run: poetry run pyinstaller bobalkkagi.spec

      - name: 'Upload PyInstaller Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: bobalkkagi-py310-win64
          path: dist/*.exe
          retention-days: 4
